# Generated by Django 4.2.1 on 2023-07-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=400)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=400)),
                ('Phone', models.IntegerField(max_length=10)),
                ('Male', models.BooleanField()),
                ('Female', models.BooleanField()),
                ('DOB', models.DateField()),
                ('Age', models.CharField(choices=[('1', '14-17'), ('2', '18-24'), ('3', '25-34'), ('4', '35-44')], max_length=300)),
                ('English', models.BooleanField()),
                ('Hindi', models.BooleanField()),
                ('Kannada', models.BooleanField()),
                ('Current_Address', models.CharField(max_length=400)),
                ('Permanent_Address', models.CharField(max_length=400)),
                ('Education_status', models.CharField(choices=[('1', 'Graduation'), ('2', 'Pursuing Graduation'), ('3', 'Diploma'), ('4', 'Pursuing Diploma'), ('5', 'Others')], max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='custommentor',
            name='Friday',
            field=models.CharField(choices=[('1', '3-6'), ('2', '6-9'), ('3', '12-3'), ('4', '9-12')], max_length=300),
        ),
        migrations.AlterField(
            model_name='custommentor',
            name='Monday',
            field=models.CharField(choices=[('1', '3-6'), ('2', '6-9'), ('3', '12-3'), ('4', '9-12')], max_length=300),
        ),
        migrations.AlterField(
            model_name='custommentor',
            name='Saturday',
            field=models.CharField(choices=[('1', '3-6'), ('2', '6-9'), ('3', '12-3'), ('4', '9-12')], max_length=300),
        ),
        migrations.AlterField(
            model_name='custommentor',
            name='Sunday',
            field=models.CharField(choices=[('1', '3-6'), ('2', '6-9'), ('3', '12-3'), ('4', '9-12')], max_length=300),
        ),
        migrations.AlterField(
            model_name='custommentor',
            name='Thursday',
            field=models.CharField(choices=[('1', '3-6'), ('2', '6-9'), ('3', '12-3'), ('4', '9-12')], max_length=300),
        ),
        migrations.AlterField(
            model_name='custommentor',
            name='Tuesday',
            field=models.CharField(choices=[('1', '3-6'), ('2', '6-9'), ('3', '12-3'), ('4', '9-12')], max_length=300),
        ),
        migrations.AlterField(
            model_name='custommentor',
            name='Wednesday',
            field=models.CharField(choices=[('1', '3-6'), ('2', '6-9'), ('3', '12-3'), ('4', '9-12')], max_length=300),
        ),
    ]
