# Generated by Django 4.2.1 on 2023-07-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_custommentee_alter_custommentor_friday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommentee',
            name='DOB',
            field=models.DateField(default='xx/xx/xxxx'),
        ),
        migrations.AlterField(
            model_name='custommentee',
            name='Name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='custommentee',
            name='Password',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='custommentee',
            name='Phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='custommentor',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='custommentor',
            name='Name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='custommentor',
            name='Password',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='custommentor',
            name='Qualification',
            field=models.CharField(default='', max_length=200),
        ),
    ]
