# Generated by Django 4.0.8 on 2023-07-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_student_languages_student_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
    ]
