# Generated by Django 4.0.8 on 2023-07-01 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_student_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mentorOrStudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
